### ISSUE TITLE
make pi work with expressions

### ISSUE THREAD

**Issue by bbolker** [queezzz/qzmle#1]
We don't have an MRE yet, but including `pi` (rather than e.g. a numerical constant) in the expression for the Gaussian log-likelihood causes trouble somewhere down the line (e.g. `all.vars` thinks it should be a data object or a parameter, but it's really neither).

**Comment by bbolker** [comment]
An MRE could look like this: 

```r
library(Deriv)
ee <- loglik_list$dnorm$expr
Deriv(ee,"mean")
```

(except that's not a real MRE). Also see the [reprex package](https://www.tidyverse.org/help/)

**Comment by queezzz** [comment]
Fixed by declaring parameters in the log-likelihood list so it won't recognize pi as a parameter.
